### PR TITLE
Add React app

### PR DESCRIPTION
**Pull request by ruhee**
Introduces fresh React app using `create-react-app` (with TypeScript). I named it `pdf-gen` because naming is hard 😅 

To run, you'll need to [install Yarn](https://classic.yarnpkg.com/en/docs/install/#mac-stable) (the quickest way is `brew install yarn`).

Then:

```bash
$ cd demoapp/pdf-gen
$ yarn install
$ yarn start
```

You should see the Create React App demo screen on `localhost:3000`:

Screen Shot 2020-07-21 at 4 18 05 PM

### CODE REVIEW

**Comment by ruhee** [comment]
@himran I didn't create a Django app, just a React app (which can have hyphens). Should this be a React project _inside_ of a Django app?

**Comment by himran92** [comment]
> @himran I didn't create a Django app, just a React app (which can have hyphens). Should this be a React project _inside_ of a Django app?



> @himran I didn't create a Django app, just a React app (which can have hyphens). Should this be a React project _inside_ of a Django app?

Hello Ruhee, you are right. I searched more. 
It would be a simple react app and no need for mentioning it in the installed apps too. 
And also looked for the project structure. it comes under the root level:

root : demoapp
  - demoapp
      - performs
  - react app

**Comment by ruhee** [comment]
@himran92 Ah okay cool! I wasn't sure if I was interpreting the project structure wrong, thank you for checking. So I should move the react app back up a level, yes? 

```
demoapp
  |
  |- demoapp
  |
  |- pdf-gen (react)
```

If you think the naming will be a problem I can just regenerate one without a hyphen, too.

**Comment by himran92** [comment]
> @himran92 Ah okay cool! I wasn't sure if I was interpreting the project structure wrong, thank you for checking. So I should move the react app back up a level, yes?
> 
> ```
> demoapp
>   |
>   |- demoapp
>   |
>   |- pdf-gen (react)
> ```
> 
> If you think the naming will be a problem I can just regenerate one without a hyphen, too.

Yes back up a level. 
The naming would be fine :) with a hyphen too as its completely following react standards

**Pull request merged**
